% File generated by compile_lrs([theory],lr_compiler_output.pl)
% at 2011/10/28 22:59:30

:- multifile fun/1.
:- multifile if/2.



% Lexical class "q1"
fun q1_0(+,-).
q1_0(A,A)if true.

kac_kac--->q1_0((@lex_nn(decl_i,plus,e_list),phon:[a_ kac_kac])).
mgel_mgl--->q1_0((@lex_nn(decl_i,plus,e_list),phon:[a_ mgel_mgl])).
xe_x--->q1_0((@lex_nn(decl_e,plus,e_list),phon:[a_ xe_x])).
mthvare_mthvar--->q1_0((@lex_nn(decl_e,plus,e_list),phon:[a_ mthvare_mthvar])).
dghe_dgh--->q1_0((@lex_nn(decl_e,plus,e_list),phon:[a_ dghe_dgh])).
ghvino_ghvin--->q1_0((@lex_nn(decl_e,minus,e_list),phon:[a_ ghvino_ghvin])).
chai_cha--->q1_0((@lex_nn(decl_e,minus,e_list),phon:[a_ chai_cha])).
gogo_gogo--->q1_0((@lex_nn(decl_ou,plus,e_list),phon:[a_ gogo_gogo])).
pepela_pepl--->q1_0((@lex_nn(decl_a,plus,e_list),phon:[a_ pepela_pepl])).
manqana_manqan--->q1_0((@lex_nn(decl_a,plus,e_list),phon:[a_ manqana_manqan])).
qal_qal--->q1_0((@lex_nn(decl_i,plus,e_list),phon:[a_ qal_qal])).
dzaghl_dzaghl--->q1_0((@lex_nn(decl_i,plus,e_list),phon:[a_ dzaghl_dzaghl])).
mamakac_mamakac--->q1_0((@lex_nn(decl_i,plus,e_list),phon:[a_ mamakac_mamakac])).
rol_rol--->q1_0((@lex_nn(decl_i,plus,[@n_comp_ss(sing)]),phon:[a_ rol_rol])).
natcil_natcil--->q1_0((@lex_nn(decl_i,plus,[@n_comp_ss(sing)]),phon:[a_ natcil_natcil])).
sarecx_sarecx--->q1_0((@lex_nn(decl_i,minus,e_list),phon:[a_ sarecx_sarecx])).
kompiuter_kompiuter--->q1_0((@lex_nn(decl_i,plus,e_list),phon:[a_ kompiuter_kompiuter])).
tcign_tcign--->q1_0((@lex_nn(decl_i,plus,e_list),phon:[a_ tcign_tcign])).
tceril_tceril--->q1_0((@lex_nn(decl_i,plus,e_list),phon:[a_ tceril_tceril])).
shvil_shvil--->q1_0((@lex_nn(decl_i,plus,[@n_comp_ss(sing)]),phon:[a_ shvil_shvil])).
student_student--->q1_0((@lex_nn(decl_i,plus,e_list),phon:[a_ student_student])).
bitch_bitch--->q1_0((@lex_nn(decl_i,plus,e_list),phon:[a_ bitch_bitch])).
bavshv_bavshv--->q1_0((@lex_nn(decl_i,plus,e_list),phon:[a_ bavshv_bavshv])).
thok_thok--->q1_0((@lex_nn(decl_i,plus,[@n_comp_ss(sing)]),phon:[a_ thok_thok])).
ghobe_ghob--->q1_0((@lex_nn(decl_e,plus,e_list),phon:[a_ ghobe_ghob])).
saxl_saxl--->q1_0((@lex_nn(decl_i,plus,[@n_comp_ss(_-num)]),phon:[a_ saxl_saxl])).
gamocda_gamocd--->q1_0((@lex_nn(decl_a,plus,e_list),phon:[a_ gamocda_gamocd])).
kithxulobs--->q1_0((@verb([@arg(nom,sing,per3),@arg(dat,_-num,per3)],[],prs),phon:[a_ kithxulobs])).
kithxuloben--->q1_0((@verb([@arg(nom,plur,per3),@arg(dat,_-num,per3)],[],prs),phon:[a_ kithxuloben])).
tcaikithxa--->q1_0((@verb([@arg(erg,sing,per3),@arg(nom,_-num,per3)],[],pst),phon:[a_ tcaikithxa])).
vkithxulobdith--->q1_0((@verb([@arg(nom,plur,per1),@arg(dat,_-num,per3)],[],psc),phon:[a_ vkithxulobdith])).
gzavnis--->q1_0((@verb([@arg(nom,sing,per3),@arg(dat,_-num,per3)],[@arg(com,_-num,_-pers)],prs),phon:[a_ gzavnis])).
gaagzavna--->q1_0((@verb([@arg(erg,sing,per3),@arg(nom,_-num,per3)],[@arg(com,_-num,_-pers)],pst),phon:[a_ gaagzavna])).
gavagzavne--->q1_0((@verb([@arg(erg,sing,per1),@arg(nom,_-num,per3)],[@arg(com,_-num,_-pers)],pst),phon:[a_ gavagzavne])).
agzavnith--->q1_0((@verb([@arg(nom,plur,per2),@arg(dat,_-num,per3)],[@arg(com,_-num,_-pers)],prs),phon:[a_ agzavnith])).
gagigzavne--->q1_0((@verb([@arg(erg,sing,per1),@arg(dat,sing,per2),@arg(nom,_-num,per3)],[@arg(com,_-num,_-pers)],pst),phon:[a_ gagigzavne])).
gaaba--->q1_0((@verb([@arg(erg,sing,per3),@arg(nom,_-num,per3)],[@arg(abl1,_-num,_-pers),@arg(ter,_-num,_-pers)],pst),phon:[a_ gaaba])).
gagibav--->q1_0((@verb([@arg(nom,sing,per1),@arg(dat,sing,per2),@arg(dat,_-num,per3)],[@arg(abl1,_-num,_-pers),@arg(ter,_-num,_-pers)],fut),phon:[a_ gagibav])).
me--->q1_0((@pn((nom;erg;dat),sing,per1),phon:[a_ me])).
me--->q1_0((@pn((nom;erg;dat),sing,per1),phon:[a_ me])).
me--->q1_0((@pn((nom;erg;dat),sing,per1),phon:[a_ me])).
chemi--->q1_0((@pn(gen,sing,per1),phon:[a_ chemi])).
chemidan--->q1_0((@pn(abl1,sing,per1),phon:[a_ chemidan])).
chemgan--->q1_0((@pn(abl2,sing,per1),phon:[a_ chemgan])).
chemthan--->q1_0((@pn(com,sing,per1),phon:[a_ chemthan])).
chemamde--->q1_0((@pn(ter,sing,per1),phon:[a_ chemamde])).
chemi--->q1_0(((@pn((A-nom_c-case,nom_c),sing,per1),cat:head:(poss_pn,mod:[@noun_ss(mod_case(A-nom_c-case),_-num,_-spec,_-list)])),phon:[a_ chemi])).
chems--->q1_0(((@pn((A-dat_c-case,dat_c),sing,per1),cat:head:(poss_pn,mod:[@noun_ss(mod_case(A-dat_c-case),_-num,_-spec,_-list)])),phon:[a_ chems])).
chemma--->q1_0(((@pn((A-erg_c-case,erg_c),sing,per1),cat:head:(poss_pn,mod:[@noun_ss(mod_case(A-erg_c-case),_-num,_-spec,_-list)])),phon:[a_ chemma])).
chven--->q1_0((@pn((nom;erg;dat),plur,per1),phon:[a_ chven])).
chven--->q1_0((@pn((nom;erg;dat),plur,per1),phon:[a_ chven])).
chven--->q1_0((@pn((nom;erg;dat),plur,per1),phon:[a_ chven])).
chveni--->q1_0((@pn(gen,plur,per1),phon:[a_ chveni])).
chvenidan--->q1_0((@pn(abl1,plur,per1),phon:[a_ chvenidan])).
chvengan--->q1_0((@pn(abl2,plur,per1),phon:[a_ chvengan])).
chventhan--->q1_0((@pn(com,plur,per1),phon:[a_ chventhan])).
chvenamde--->q1_0((@pn(ter,plur,per1),phon:[a_ chvenamde])).
chveni--->q1_0(((@pn((A-nom_c-case,nom_c),plur,per1),cat:head:(poss_pn,mod:[@noun_ss(mod_case(A-nom_c-case),_-num,_-spec,_-list)])),phon:[a_ chveni])).
chvens--->q1_0(((@pn((A-dat_c-case,dat_c),plur,per1),cat:head:(poss_pn,mod:[@noun_ss(mod_case(A-dat_c-case),_-num,_-spec,_-list)])),phon:[a_ chvens])).
chvenma--->q1_0(((@pn((A-erg_c-case,erg_c),plur,per1),cat:head:(poss_pn,mod:[@noun_ss(mod_case(A-erg_c-case),_-num,_-spec,_-list)])),phon:[a_ chvenma])).
shen--->q1_0((@pn((nom;erg;dat),sing,per2),phon:[a_ shen])).
shen--->q1_0((@pn((nom;erg;dat),sing,per2),phon:[a_ shen])).
shen--->q1_0((@pn((nom;erg;dat),sing,per2),phon:[a_ shen])).
sheni--->q1_0((@pn(gen,sing,per2),phon:[a_ sheni])).
shenidan--->q1_0((@pn(abl1,sing,per2),phon:[a_ shenidan])).
shengan--->q1_0((@pn(abl2,sing,per2),phon:[a_ shengan])).
shenthan--->q1_0((@pn(com,sing,per2),phon:[a_ shenthan])).
shenamde--->q1_0((@pn(ter,sing,per2),phon:[a_ shenamde])).
sheni--->q1_0(((@pn((A-nom_c-case,nom_c),sing,per2),cat:head:(poss_pn,mod:[@noun_ss(mod_case(A-nom_c-case),_-num,_-spec,_-list)])),phon:[a_ sheni])).
shens--->q1_0(((@pn((A-dat_c-case,dat_c),sing,per2),cat:head:(poss_pn,mod:[@noun_ss(mod_case(A-dat_c-case),_-num,_-spec,_-list)])),phon:[a_ shens])).
shenma--->q1_0(((@pn((A-erg_c-case,erg_c),sing,per2),cat:head:(poss_pn,mod:[@noun_ss(mod_case(A-erg_c-case),_-num,_-spec,_-list)])),phon:[a_ shenma])).
thqven--->q1_0((@pn((nom;erg;dat),plur,per2),phon:[a_ thqven])).
thqven--->q1_0((@pn((nom;erg;dat),plur,per2),phon:[a_ thqven])).
thqven--->q1_0((@pn((nom;erg;dat),plur,per2),phon:[a_ thqven])).
thqveni--->q1_0((@pn(gen,plur,per2),phon:[a_ thqveni])).
thqvenidan--->q1_0((@pn(abl1,plur,per2),phon:[a_ thqvenidan])).
thqvengan--->q1_0((@pn(abl2,plur,per2),phon:[a_ thqvengan])).
thqventhan--->q1_0((@pn(com,plur,per2),phon:[a_ thqventhan])).
thqvenamde--->q1_0((@pn(ter,plur,per2),phon:[a_ thqvenamde])).
thqveni--->q1_0(((@pn((A-nom_c-case,nom_c),plur,per2),cat:head:(poss_pn,mod:[@noun_ss(mod_case(A-nom_c-case),_-num,_-spec,_-list)])),phon:[a_ thqveni])).
thqvens--->q1_0(((@pn((A-dat_c-case,dat_c),plur,per2),cat:head:(poss_pn,mod:[@noun_ss(mod_case(A-dat_c-case),_-num,_-spec,_-list)])),phon:[a_ thqvens])).
thqvenma--->q1_0(((@pn((A-erg_c-case,erg_c),plur,per2),cat:head:(poss_pn,mod:[@noun_ss(mod_case(A-erg_c-case),_-num,_-spec,_-list)])),phon:[a_ thqvenma])).
is--->q1_0((@pn(nom,sing,per3),phon:[a_ is])).
igi--->q1_0((@pn(nom,sing,per3),phon:[a_ igi])).
mas--->q1_0((@pn(dat,sing,per3),phon:[a_ mas])).
man--->q1_0((@pn(erg,sing,per3),phon:[a_ man])).
misith--->q1_0((@pn(ins,sing,per3),phon:[a_ misith])).
misi--->q1_0((@pn(gen,sing,per3),phon:[a_ misi])).
misgan--->q1_0((@pn((abl2;abl1),sing,per3),phon:[a_ misgan])).
misgan--->q1_0((@pn((abl2;abl1),sing,per3),phon:[a_ misgan])).
masthan--->q1_0((@pn(com,sing,per3),phon:[a_ masthan])).
misi--->q1_0(((@pn((A-nom_c-case,nom_c),sing,per3),cat:head:(poss_pn,mod:[@noun_ss(mod_case(A-nom_c-case),_-num,_-spec,_-list)])),phon:[a_ misi])).
mis--->q1_0(((@pn((A-dat_c-case,dat_c),sing,per3),cat:head:(poss_pn,mod:[@noun_ss(mod_case(A-dat_c-case),_-num,_-spec,_-list)])),phon:[a_ mis])).
misma--->q1_0(((@pn((A-erg_c-case,erg_c),sing,per3),cat:head:(poss_pn,mod:[@noun_ss(mod_case(A-erg_c-case),_-num,_-spec,_-list)])),phon:[a_ misma])).
isini--->q1_0((@pn(nom,plur,per3),phon:[a_ isini])).
math--->q1_0((@pn((erg;dat),plur,per3),phon:[a_ math])).
math--->q1_0((@pn((erg;dat),plur,per3),phon:[a_ math])).
mathi--->q1_0((@pn(gen,plur,per3),phon:[a_ mathi])).
mathgan--->q1_0((@pn((abl1;abl2),plur,per3),phon:[a_ mathgan])).
mathgan--->q1_0((@pn((abl1;abl2),plur,per3),phon:[a_ mathgan])).
maththan--->q1_0((@pn(com,plur,per3),phon:[a_ maththan])).
mathi--->q1_0(((@pn((A-nom_c-case,nom_c),plur,per3),cat:head:(poss_pn,mod:[@noun_ss(mod_case(A-nom_c-case),_-num,_-spec,_-list)])),phon:[a_ mathi])).
math--->q1_0(((@pn((A-dat_c-case,dat_c),plur,per3),cat:head:(poss_pn,mod:[@noun_ss(mod_case(A-dat_c-case),_-num,_-spec,_-list)])),phon:[a_ math])).
mathma--->q1_0(((@pn((A-erg_c-case,erg_c),plur,per3),cat:head:(poss_pn,mod:[@noun_ss(mod_case(A-erg_c-case),_-num,_-spec,_-list)])),phon:[a_ mathma])).
didi_did--->q1_0((@lex_aa(decl_i),phon:[a_ didi_did])).
lamazi_lamaz--->q1_0((@lex_aa(decl_i),phon:[a_ lamazi_lamaz])).
maghali_maghl--->q1_0((@lex_aa(decl_i),phon:[a_ maghali_maghl])).
tcitheli_tcithl--->q1_0((@lex_aa(decl_i),phon:[a_ tcitheli_tcithl])).
patara_patar--->q1_0((@lex_aa(decl_a),phon:[a_ patara_patar])).
mtcvane_mtcvane--->q1_0((@lex_aa(decl_e),phon:[a_ mtcvane_mtcvane])).
axalgazrda_axalgazrd--->q1_0((@lex_aa(decl_a),phon:[a_ axalgazrda_axalgazrd])).
cru_cru--->q1_0((@lex_aa(decl_ou),phon:[a_ cru_cru])).
ucxo_ucxo--->q1_0((@lex_aa(decl_ou),phon:[a_ ucxo_ucxo])).
ubralo_ubralo--->q1_0((@lex_aa(decl_ou),phon:[a_ ubralo_ubralo])).
mokle_mokle--->q1_0((@lex_aa(decl_ou),phon:[a_ mokle_mokle])).
saintereso_saintereso--->q1_0((@lex_aa(decl_ou),phon:[a_ saintereso_saintereso])).
bejithi_bejith--->q1_0((@lex_aa(decl_ou),phon:[a_ bejithi_bejith])).
yvela_yvela--->q1_0((@lex_qq(decl_ou),phon:[a_ yvela_yvela])).
romelighaca_romelighaca--->q1_0((@lex_qq(decl_a),phon:[a_ romelighaca_romelighaca])).
zogierthi_zogierth--->q1_0((@lex_qq(decl_i),phon:[a_ zogierthi_zogierth])).
icini_icinod_icin_icineb--->q1_0((@lexeme_verb(e_list,e_list,e_list,@dynamic(conj1,minus,@an_en,@e_a,_-tense(_-list))),phon:[a_ icini_icinod_icin_icineb])).
icini_icinod_icin_icineb--->q1_0((@lexeme_verb([a_ ga,a_ cha],e_list,e_list,@dynamic(conj1,minus,@an_en,@e_a,(pst;fut))),phon:[a_ icini_icinod_icin_icineb])).
icini_icinod_icin_icineb--->q1_0((@lexeme_verb([a_ ga,a_ cha],e_list,e_list,@dynamic(conj1,minus,@an_en,@e_a,(pst;fut))),phon:[a_ icini_icinod_icin_icineb])).
rbi_rbod_irbin_irben--->q1_0((@lexeme_verb((e_list;[a_ mi,a_ mo,a_ a,a_ she,a_ ga,a_ cha,a_ da,a_ gada,a_ gadmo,a_ amo,a_ gamo,a_ chamo,a_ shemo,a_ mimo]),e_list,e_list,@dynamic(conj1,minus,@an_en,@e_a,_-tense(_-list))),phon:[a_ rbi_rbod_irbin_irben])).
rbi_rbod_irbin_irben--->q1_0((@lexeme_verb((e_list;[a_ mi,a_ mo,a_ a,a_ she,a_ ga,a_ cha,a_ da,a_ gada,a_ gadmo,a_ amo,a_ gamo,a_ chamo,a_ shemo,a_ mimo]),e_list,e_list,@dynamic(conj1,minus,@an_en,@e_a,_-tense(_-list))),phon:[a_ rbi_rbod_irbin_irben])).
dum_dumd_idum_idumeb--->q1_0((@lexeme_verb(e_list,e_list,e_list,@dynamic(conj1,plus,@an_en,@e_a,_-tense(_-list))),phon:[a_ dum_dumd_idum_idumeb])).
bghavi_bghaod_ibghavl_ibghavleb--->q1_0((@lexeme_verb((e_list;[a_ da]),e_list,e_list,@dynamic(conj1,both,@an_en,@e_a,_-tense(_-list))),phon:[a_ bghavi_bghaod_ibghavl_ibghavleb])).
bghavi_bghaod_ibghavl_ibghavleb--->q1_0((@lexeme_verb((e_list;[a_ da]),e_list,e_list,@dynamic(conj1,both,@an_en,@e_a,_-tense(_-list))),phon:[a_ bghavi_bghaod_ibghavl_ibghavleb])).
mushaob_mushaobd_imushav_imushaveb--->q1_0((@lexeme_verb(e_list,e_list,e_list,@dynamic(conj1,minus,@en_en,@e_a,_-tense(_-list))),phon:[a_ mushaob_mushaobd_imushav_imushaveb])).
thamashob_tamashobd_itamash_itamasheb--->q1_0((@lexeme_verb(e_list,[@arg(_-arg_c,_-num,_-pers)],e_list,@dynamic(conj1,minus,@en_en,@e_a,_-tense(_-list))),phon:[a_ thamashob_tamashobd_itamash_itamasheb])).
tcer_tcerd_tcer_tcer--->q1_0((@lexeme_verb(e_list,[@arg(_-arg_c,_-num,_-pers)],e_list,@dynamic(conj1,minus,@en_en,@e_a,(prs;psc;pst))),phon:[a_ tcer_tcerd_tcer_tcer])).
tcer_tcerd_tcer_tcer--->q1_0((@lexeme_verb(e_list,[@arg(_-arg_c,_-num,_-pers)],e_list,@dynamic(conj1,minus,@en_en,@e_a,(prs;psc;pst))),phon:[a_ tcer_tcerd_tcer_tcer])).
tcer_tcerd_tcer_tcer--->q1_0((@lexeme_verb(e_list,[@arg(_-arg_c,_-num,_-pers)],e_list,@dynamic(conj1,minus,@en_en,@e_a,(prs;psc;pst))),phon:[a_ tcer_tcerd_tcer_tcer])).
tcer_tcerd_tcer_tcer--->q1_0((@lexeme_verb([a_ da,a_ ga,a_ gamo,a_ chamo],[@arg(_-arg_c,_-num,_-pers)],e_list,@dynamic(conj1,minus,@en_en,@e_a,(pst;fut))),phon:[a_ tcer_tcerd_tcer_tcer])).
tcer_tcerd_tcer_tcer--->q1_0((@lexeme_verb([a_ da,a_ ga,a_ gamo,a_ chamo],[@arg(_-arg_c,_-num,_-pers)],e_list,@dynamic(conj1,minus,@en_en,@e_a,(pst;fut))),phon:[a_ tcer_tcerd_tcer_tcer])).
tcer_tcerd_tcer_tcer--->q1_0((@lexeme_verb([a_ cha],[@arg(_-arg_c,_-num,_-pers)],[@arg(ine,num,per3)],@dynamic(conj1,minus,@en_en,@e_a,(pst;fut))),phon:[a_ tcer_tcerd_tcer_tcer])).
tcer_tcerd_tcer_tcer--->q1_0((@lexeme_verb([a_ cha],[@arg(_-arg_c,_-num,_-pers)],[@arg(ine,num,per3)],@dynamic(conj1,minus,@en_en,@e_a,(pst;fut))),phon:[a_ tcer_tcerd_tcer_tcer])).
tcer_tcerd_tcer_tcer--->q1_0((@lexeme_verb([a_ amo],[@arg(_-arg_c,_-num,_-pers)],[@arg(abl1,num,per3)],@dynamic(conj1,minus,@en_en,@e_a,(pst;fut))),phon:[a_ tcer_tcerd_tcer_tcer])).
tcer_tcerd_tcer_tcer--->q1_0((@lexeme_verb([a_ amo],[@arg(_-arg_c,_-num,_-pers)],[@arg(abl1,num,per3)],@dynamic(conj1,minus,@en_en,@e_a,(pst;fut))),phon:[a_ tcer_tcerd_tcer_tcer])).
tcer_tcerd_tcer_tcer--->q1_0((@lexeme_verb([a_ gada,a_ gadmo],[@arg(_-arg_c,_-num,_-pers)],[@arg((abl1;abl2),num,per3),@arg(ine,num,per3)],@dynamic(conj1,minus,@en_en,@e_a,(pst;fut))),phon:[a_ tcer_tcerd_tcer_tcer])).
tcer_tcerd_tcer_tcer--->q1_0((@lexeme_verb([a_ gada,a_ gadmo],[@arg(_-arg_c,_-num,_-pers)],[@arg((abl1;abl2),num,per3),@arg(ine,num,per3)],@dynamic(conj1,minus,@en_en,@e_a,(pst;fut))),phon:[a_ tcer_tcerd_tcer_tcer])).
tcer_tcerd_tcer_tcer--->q1_0((@lexeme_verb([a_ gada,a_ gadmo],[@arg(_-arg_c,_-num,_-pers)],[@arg((abl1;abl2),num,per3),@arg(ine,num,per3)],@dynamic(conj1,minus,@en_en,@e_a,(pst;fut))),phon:[a_ tcer_tcerd_tcer_tcer])).
tcer_tcerd_tcer_tcer--->q1_0((@lexeme_verb([a_ gada,a_ gadmo],[@arg(_-arg_c,_-num,_-pers)],[@arg((abl1;abl2),num,per3),@arg(ine,num,per3)],@dynamic(conj1,minus,@en_en,@e_a,(pst;fut))),phon:[a_ tcer_tcerd_tcer_tcer])).
zrdi_zrdid_zard_zrdi--->q1_0((@lexeme_verb(e_list,e_list,e_list,@dynamic(conj2,minus,@an_an,@e_a,(prs;psc;pst))),phon:[a_ zrdi_zrdid_zard_zrdi])).
zrdi_zrdid_zard_zrdi--->q1_0((@lexeme_verb(e_list,e_list,e_list,@dynamic(conj2,minus,@an_an,@e_a,(prs;psc;pst))),phon:[a_ zrdi_zrdid_zard_zrdi])).
zrdi_zrdid_zard_zrdi--->q1_0((@lexeme_verb(e_list,e_list,e_list,@dynamic(conj2,minus,@an_an,@e_a,(prs;psc;pst))),phon:[a_ zrdi_zrdid_zard_zrdi])).
zrdi_zrdid_zard_zrdi--->q1_0((@lexeme_verb([a_ ga,a_ agh],e_list,e_list,@dynamic(conj2,minus,@an_an,@e_a,(pst;fut))),phon:[a_ zrdi_zrdid_zard_zrdi])).
zrdi_zrdid_zard_zrdi--->q1_0((@lexeme_verb([a_ ga,a_ agh],e_list,e_list,@dynamic(conj2,minus,@an_an,@e_a,(pst;fut))),phon:[a_ zrdi_zrdid_zard_zrdi])).
ichivi_ichiod_ichivl_ichivleb--->q1_0((@lexeme_verb(e_list,e_list,e_list,@dynamic(conj2,both,@an_en,@e_a,_-tense(_-list))),phon:[a_ ichivi_ichiod_ichivl_ichivleb])).
cini_cinod_cin_cineb--->q1_0((@lexeme_verb([a_ da],e_list,e_list,@dynamic(conj2,minus,@an_en,@e_a,_-tense(_-list))),phon:[a_ cini_cinod_cin_cineb])).
imaleb_imalebod_imal_imaleb--->q1_0((@lexeme_verb(e_list,e_list,e_list,@static(conj1,@e_a,(prs;psc;pst))),phon:[a_ imaleb_imalebod_imal_imaleb])).
imaleb_imalebod_imal_imaleb--->q1_0((@lexeme_verb(e_list,e_list,e_list,@static(conj1,@e_a,(prs;psc;pst))),phon:[a_ imaleb_imalebod_imal_imaleb])).
imaleb_imalebod_imal_imaleb--->q1_0((@lexeme_verb(e_list,e_list,e_list,@static(conj1,@e_a,(prs;psc;pst))),phon:[a_ imaleb_imalebod_imal_imaleb])).
imaleb_imalebod_imal_imaleb--->q1_0((@lexeme_verb([a_ da,a_ mi,a_ gada],e_list,e_list,@static(conj1,@e_a,(pst;fut))),phon:[a_ imaleb_imalebod_imal_imaleb])).
imaleb_imalebod_imal_imaleb--->q1_0((@lexeme_verb([a_ da,a_ mi,a_ gada],e_list,e_list,@static(conj1,@e_a,(pst;fut))),phon:[a_ imaleb_imalebod_imal_imaleb])).
imaleb_imalebod_imal_imaleb--->q1_0((@lexeme_verb([a_ cha],e_list,[@arg(ine,_-num,_-pers)],@static(conj1,@e_a,(pst;fut))),phon:[a_ imaleb_imalebod_imal_imaleb])).
imaleb_imalebod_imal_imaleb--->q1_0((@lexeme_verb([a_ cha],e_list,[@arg(ine,_-num,_-pers)],@static(conj1,@e_a,(pst;fut))),phon:[a_ imaleb_imalebod_imal_imaleb])).
tcvdeb_tcvdebod_tcvd_tcvdeb--->q1_0((@lexeme_verb(e_list,e_list,e_list,@static(conj2,@i_a,(prs;psc;pst))),phon:[a_ tcvdeb_tcvdebod_tcvd_tcvdeb])).
tcvdeb_tcvdebod_tcvd_tcvdeb--->q1_0((@lexeme_verb(e_list,e_list,e_list,@static(conj2,@i_a,(prs;psc;pst))),phon:[a_ tcvdeb_tcvdebod_tcvd_tcvdeb])).
tcvdeb_tcvdebod_tcvd_tcvdeb--->q1_0((@lexeme_verb(e_list,e_list,e_list,@static(conj2,@i_a,(prs;psc;pst))),phon:[a_ tcvdeb_tcvdebod_tcvd_tcvdeb])).
tcvdeb_tcvdebod_tcvd_tcvdeb--->q1_0((@lexeme_verb([a_ mi,a_ mo,a_ cha,a_ gada,a_ gadmo,a_ she,a_ tca],e_list,e_list,@static(conj2,@i_a,(pst;fut))),phon:[a_ tcvdeb_tcvdebod_tcvd_tcvdeb])).
tcvdeb_tcvdebod_tcvd_tcvdeb--->q1_0((@lexeme_verb([a_ mi,a_ mo,a_ cha,a_ gada,a_ gadmo,a_ she,a_ tca],e_list,e_list,@static(conj2,@i_a,(pst;fut))),phon:[a_ tcvdeb_tcvdebod_tcvd_tcvdeb])).
endob_endobod_end_endob--->q1_0((@lexeme_verb(e_list,e_list,e_list,@static(conj2,@e_o,(prs;psc;pst))),phon:[a_ endob_endobod_end_endob])).
endob_endobod_end_endob--->q1_0((@lexeme_verb(e_list,e_list,e_list,@static(conj2,@e_o,(prs;psc;pst))),phon:[a_ endob_endobod_end_endob])).
endob_endobod_end_endob--->q1_0((@lexeme_verb(e_list,e_list,e_list,@static(conj2,@e_o,(prs;psc;pst))),phon:[a_ endob_endobod_end_endob])).
endob_endobod_end_endob--->q1_0((@lexeme_verb([a_ mi,a_ mo,a_ ga],e_list,e_list,@static(conj2,@e_o,(pst;fut))),phon:[a_ endob_endobod_end_endob])).
endob_endobod_end_endob--->q1_0((@lexeme_verb([a_ mi,a_ mo,a_ ga],e_list,e_list,@static(conj2,@e_o,(pst;fut))),phon:[a_ endob_endobod_end_endob])).
ibrazdeb_ibrazdebod_ibrazd_ibrazdeb--->q1_0((@lexeme_verb(e_list,e_list,e_list,@static(conj2,@e_o,(prs;psc))),phon:[a_ ibrazdeb_ibrazdebod_ibrazd_ibrazdeb])).
ibrazdeb_ibrazdebod_ibrazd_ibrazdeb--->q1_0((@lexeme_verb(e_list,e_list,e_list,@static(conj2,@e_o,(prs;psc))),phon:[a_ ibrazdeb_ibrazdebod_ibrazd_ibrazdeb])).
ibrazdeb_ibrazdebod_ibrazd_ibrazdeb--->q1_0((@lexeme_verb([a_ ga],e_list,e_list,@static(conj2,@e_o,(pst;fut))),phon:[a_ ibrazdeb_ibrazdebod_ibrazd_ibrazdeb])).
ibrazdeb_ibrazdebod_ibrazd_ibrazdeb--->q1_0((@lexeme_verb([a_ ga],e_list,e_list,@static(conj2,@e_o,(pst;fut))),phon:[a_ ibrazdeb_ibrazdebod_ibrazd_ibrazdeb])).
shia_shioda_empty_eshieba--->q1_0((@lexeme_verb(e_list,e_list,e_list,@stative(conj1,minus,_-list,(prs;psc;fut))),phon:[a_ shia_shioda_empty_eshieba])).
shia_shioda_empty_eshieba--->q1_0((@lexeme_verb(e_list,e_list,e_list,@stative(conj1,minus,_-list,(prs;psc;fut))),phon:[a_ shia_shioda_empty_eshieba])).
shia_shioda_empty_eshieba--->q1_0((@lexeme_verb(e_list,e_list,e_list,@stative(conj1,minus,_-list,(prs;psc;fut))),phon:[a_ shia_shioda_empty_eshieba])).
tcons_tconda_etcona_etconeba--->q1_0((@lexeme_verb([a_ mo],e_list,e_list,@stative(conj2,plus,@e,_-tense(_-list))),phon:[a_ tcons_tconda_etcona_etconeba])).
iyvars_iyvarda_empty_eyvareba--->q1_0((@lexeme_verb(e_list,e_list,e_list,@stative(conj2,plus,_-list,(prs;psc;fut))),phon:[a_ iyvars_iyvarda_empty_eyvareba])).
iyvars_iyvarda_empty_eyvareba--->q1_0((@lexeme_verb(e_list,e_list,e_list,@stative(conj2,plus,_-list,(prs;psc;fut))),phon:[a_ iyvars_iyvarda_empty_eyvareba])).
iyvars_iyvarda_empty_eyvareba--->q1_0((@lexeme_verb(e_list,e_list,e_list,@stative(conj2,plus,_-list,(prs;psc;fut))),phon:[a_ iyvars_iyvarda_empty_eyvareba])).
enatreba_enatreboda_enatra_enatreba--->q1_0((@lexeme_verb([a_ mo],e_list,e_list,@stative(conj2,minus,@e,(pst;fut))),phon:[a_ enatreba_enatreboda_enatra_enatreba])).
enatreba_enatreboda_enatra_enatreba--->q1_0((@lexeme_verb([a_ mo],e_list,e_list,@stative(conj2,minus,@e,(pst;fut))),phon:[a_ enatreba_enatreboda_enatra_enatreba])).
enatreba_enatreboda_enatra_enatreba--->q1_0((@lexeme_verb(e_list,e_list,e_list,@stative(conj2,minus,_-list,(prs;psc))),phon:[a_ enatreba_enatreboda_enatra_enatreba])).
enatreba_enatreboda_enatra_enatreba--->q1_0((@lexeme_verb(e_list,e_list,e_list,@stative(conj2,minus,_-list,(prs;psc))),phon:[a_ enatreba_enatreboda_enatra_enatreba])).
eshinia_eshinoda_eshinda_eshindeba--->q1_0((@lexeme_verb(e_list,e_list,[@arg(gen,_-num,_-pers)],@stative(conj1,minus,_-list,(prs;psc))),phon:[a_ eshinia_eshinoda_eshinda_eshindeba])).
eshinia_eshinoda_eshinda_eshindeba--->q1_0((@lexeme_verb(e_list,e_list,[@arg(gen,_-num,_-pers)],@stative(conj1,minus,_-list,(prs;psc))),phon:[a_ eshinia_eshinoda_eshinda_eshindeba])).
eshinia_eshinoda_eshinda_eshindeba--->q1_0((@lexeme_verb([a_ she],e_list,[@arg(gen,_-num,_-pers)],@stative(conj1,minus,_-list,(pst;fut))),phon:[a_ eshinia_eshinoda_eshinda_eshindeba])).
eshinia_eshinoda_eshinda_eshindeba--->q1_0((@lexeme_verb([a_ she],e_list,[@arg(gen,_-num,_-pers)],@stative(conj1,minus,_-list,(pst;fut))),phon:[a_ eshinia_eshinoda_eshinda_eshindeba])).
